### ISSUE TITLE
Get  ID field "path" not defined in stash following the getting started steps

### ISSUE THREAD

**Issue by tehmoth** [preaction/Yancy-Backend-Static#11]
(Folliwng the Yancy::Backend::Static GETTING STARTED steps)
* Created the myapp.pl from the POD
* Ran perl myapp.pl daemon
* open http://127.0.0.1:3000/yancy
* Create an index page
* Click the "eye" 
Instead of the expected result I get

ID field "path" not defined in stash at /home/perl/perl-5.30.2/lib/site_perl/5.30.2/Yancy/Controller/Yancy.pm line 450.
445 | }
-- | --
446 | my $schema_name = $c->stash( 'schema' ) \|\| $c->stash( 'collection' )
447 | \|\| die "Schema name not defined in stash";
448 | my $id_field = $c->yancy->schema( $schema_name )->{'x-id-field'} // 'id';
449 | my $id = ref $id_field eq 'ARRAY'
450 | ? { map { $_ => $c->stash( $_ ) } grep defined $c->stash( $_ ), @$id_field }
451 | : ( $c->stash( $id_field ) // die sprintf 'ID field "%s" not defined in stash', $id_field );
452 | my $item = $c->yancy->backend->get( $schema_name => $id );
453 | if ( !$item ) {
454 | $c->reply->not_found;
455 | return;

**Comment by preaction** [comment]
Ack. I broke that back in Yancy 1.057 but apparently haven't tested it since... Instead of `*id`, it should be `*path`. I'll fix the code (and the tests which fail for the same reason). Thanks for reporting this!
